"use client";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Provider } from "react-redux";
import { Store } from "@/utils/Store";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          {children.props.title
            ? children.props.title + " - GuildMaster"
            : "GuildMaster"}
        </title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <SessionProvider>
          <Provider store={Store}>
            <main>{children}</main>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
