"use client";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Provider } from "react-redux";
import { Store, persistor } from "@/utils/Store";
import { PersistGate } from "redux-persist/integration/react";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          {children.props.title
            ? children.props.title + " - GuildMaster"
            : "GuildMaster"}
        </title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <SessionProvider>
          <Provider store={Store}>
            <PersistGate loading={null} persistor={persistor}>
              <main>{children}</main>
            </PersistGate>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
